type Translate = (key: any, options?: any) => string;

export const SECTION_IDS = {
  general: "general-settings",
  workflow: "workflow-settings",
  ai: "ai-settings",
  providers: "provider-settings",
  telemetry: "telemetry",
  integrations: "integrations",
  agentPermissions: "agent-permissions",
  toolsMcp: "tools-mcp",
  experiments: "experiments",
  dangerZone: "danger-zone",
} as const;

export const SETTING_IDS = {
  theme: "setting-theme",
  zoom: "setting-zoom",
  autoUpdate: "setting-auto-update",
  releaseChannel: "setting-release-channel",
  runtimeMode: "setting-runtime-mode",
  nodePath: "setting-node-path",
  customAppsFolder: "setting-custom-apps-folder",
  defaultChatMode: "setting-default-chat-mode",
  autoApprove: "setting-auto-approve",
  autoFix: "setting-auto-fix",
  autoExpandPreview: "setting-auto-expand-preview",
  chatEventNotification: "setting-chat-event-notification",
  thinkingBudget: "setting-thinking-budget",
  imageGenerationProvider: "setting-image-generation-provider",
  imageGenerationModel: "setting-image-generation-model",
  maxChatTurns: "setting-max-chat-turns",
  maxToolCallSteps: "setting-max-tool-call-steps",
  contextCompaction: "setting-context-compaction",
  telemetry: "setting-telemetry",
  github: "setting-github",
  vercel: "setting-vercel",
  supabase: "setting-supabase",
  neon: "setting-neon",
  nativeGit: "setting-native-git",
  blockUnsafeNpmPackages: "setting-block-unsafe-npm-packages",
  enableMcpServersForBuildMode: "setting-enable-mcp-servers-for-build-mode",
  enableSelectAppFromHomeChatInput:
    "setting-enable-select-app-from-home-chat-input",
  reset: "setting-reset",
} as const;

type SearchableSettingItem = {
  id: string;
  label: string;
  description: string;
  keywords: string[];
  sectionId: string;
  sectionLabel: string;
};

type SettingsSection = {
  id: string;
  label: string;
};

export function getSettingsSections(t: Translate): SettingsSection[] {
  return [
    { id: SECTION_IDS.general, label: t("sidebar.general") },
    { id: SECTION_IDS.workflow, label: t("sidebar.workflow") },
    { id: SECTION_IDS.ai, label: t("sidebar.ai") },
    { id: SECTION_IDS.providers, label: t("sidebar.providers") },
    { id: SECTION_IDS.telemetry, label: t("sidebar.telemetry") },
    { id: SECTION_IDS.integrations, label: t("sidebar.integrations") },
    {
      id: SECTION_IDS.agentPermissions,
      label: t("sidebar.agentPermissions"),
    },
    { id: SECTION_IDS.toolsMcp, label: t("sidebar.toolsMcp") },
    { id: SECTION_IDS.experiments, label: t("sidebar.experiments") },
    { id: SECTION_IDS.dangerZone, label: t("sidebar.dangerZone") },
  ];
}

export function getSettingsSearchIndex({
  tSettings,
  tHome,
}: {
  tSettings: Translate;
  tHome: Translate;
}): SearchableSettingItem[] {
  const sections = {
    general: tSettings("sidebar.general"),
    workflow: tSettings("sidebar.workflow"),
    ai: tSettings("sidebar.ai"),
    providers: tSettings("sidebar.providers"),
    telemetry: tSettings("sidebar.telemetry"),
    integrations: tSettings("sidebar.integrations"),
    agentPermissions: tSettings("sidebar.agentPermissions"),
    toolsMcp: tSettings("sidebar.toolsMcp"),
    experiments: tSettings("sidebar.experiments"),
    dangerZone: tSettings("sidebar.dangerZone"),
  };

  return [
    {
      id: SETTING_IDS.theme,
      label: tSettings("general.theme"),
      description: "Switch between system, light, and dark mode",
      keywords: ["dark mode", "light mode", "appearance", "color", "system"],
      sectionId: SECTION_IDS.general,
      sectionLabel: sections.general,
    },
    {
      id: SETTING_IDS.zoom,
      label: tSettings("general.zoom"),
      description: tSettings("general.zoomDescription"),
      keywords: ["font size", "magnify", "scale", "accessibility", "zoom"],
      sectionId: SECTION_IDS.general,
      sectionLabel: sections.general,
    },
    {
      id: SETTING_IDS.autoUpdate,
      label: tSettings("general.autoUpdate"),
      description: tSettings("general.autoUpdateDescription"),
      keywords: ["update", "automatic", "version", "upgrade"],
      sectionId: SECTION_IDS.general,
      sectionLabel: sections.general,
    },
    {
      id: SETTING_IDS.releaseChannel,
      label: tSettings("general.releaseChannel"),
      description: tSettings("general.releaseChannelDescription"),
      keywords: ["stable", "beta", "channel", "release", "version"],
      sectionId: SECTION_IDS.general,
      sectionLabel: sections.general,
    },
    {
      id: SETTING_IDS.runtimeMode,
      label: tSettings("general.runtimeMode"),
      description: tSettings("general.runtimeModeDescription"),
      keywords: ["node", "runtime", "bun", "environment", "docker"],
      sectionId: SECTION_IDS.general,
      sectionLabel: sections.general,
    },
    {
      id: SETTING_IDS.nodePath,
      label: tSettings("general.nodePath"),
      description: tSettings("general.nodeSelectFolder"),
      keywords: ["node", "path", "nodejs", "binary", "executable"],
      sectionId: SECTION_IDS.general,
      sectionLabel: sections.general,
    },
    {
      id: SETTING_IDS.customAppsFolder,
      label: tSettings("general.customAppsFolder"),
      description: tSettings("general.customAppsFolderDescription"),
      keywords: [
        "customize",
        "apps",
        "path",
        "folder",
        "directory",
        "dyad-apps",
      ],
      sectionId: SECTION_IDS.general,
      sectionLabel: sections.general,
    },
    {
      id: SETTING_IDS.defaultChatMode,
      label: tSettings("workflow.defaultChatMode"),
      description: tSettings("workflow.defaultChatModeDescription"),
      keywords: ["chat", "mode", "build", "agent", "mcp", "default"],
      sectionId: SECTION_IDS.workflow,
      sectionLabel: sections.workflow,
    },
    {
      id: SETTING_IDS.autoApprove,
      label: tSettings("workflow.autoApprove"),
      description: tSettings("workflow.autoApproveDescription"),
      keywords: ["approve", "automatic", "code changes", "auto"],
      sectionId: SECTION_IDS.workflow,
      sectionLabel: sections.workflow,
    },
    {
      id: SETTING_IDS.autoFix,
      label: tSettings("workflow.autoFixProblems"),
      description: tSettings("workflow.autoFixProblemsDescription"),
      keywords: [
        "fix",
        "typescript",
        "errors",
        "automatic",
        "problems",
        "auto",
      ],
      sectionId: SECTION_IDS.workflow,
      sectionLabel: sections.workflow,
    },
    {
      id: SETTING_IDS.autoExpandPreview,
      label: tSettings("workflow.autoExpandPreview"),
      description: tSettings("workflow.autoExpandPreviewDescription"),
      keywords: ["preview", "expand", "panel", "automatic", "auto"],
      sectionId: SECTION_IDS.workflow,
      sectionLabel: sections.workflow,
    },
    {
      id: SETTING_IDS.chatEventNotification,
      label: tSettings("workflow.notifications"),
      description:
        "Show native notifications when a chat response completes or a questionnaire needs your input while the app is not focused",
      keywords: [
        "notification",
        "chat",
        "complete",
        "questionnaire",
        "alert",
        "background",
      ],
      sectionId: SECTION_IDS.workflow,
      sectionLabel: sections.workflow,
    },
    {
      id: SETTING_IDS.thinkingBudget,
      label: tSettings("ai.thinkingBudget"),
      description: tSettings("ai.thinkingBudgetDescription"),
      keywords: ["thinking", "tokens", "budget", "reasoning", "ai"],
      sectionId: SECTION_IDS.ai,
      sectionLabel: sections.ai,
    },
    {
      id: SETTING_IDS.imageGenerationProvider,
      label: tSettings("ai.imageGenerationProvider"),
      description: tSettings("ai.imageGenerationProviderDescription"),
      keywords: [
        "image",
        "generation",
        "provider",
        "openai",
        "openrouter",
        "google",
        "minimax",
        "xai",
      ],
      sectionId: SECTION_IDS.ai,
      sectionLabel: sections.ai,
    },
    {
      id: SETTING_IDS.imageGenerationModel,
      label: tSettings("ai.imageGenerationModel"),
      description: tSettings("ai.imageGenerationModelDescription"),
      keywords: [
        "image",
        "generation",
        "model",
        "gpt-image",
        "gemini",
        "grok",
      ],
      sectionId: SECTION_IDS.ai,
      sectionLabel: sections.ai,
    },
    {
      id: SETTING_IDS.maxChatTurns,
      label: tSettings("ai.maxChatTurns"),
      description: tSettings("ai.maxChatTurnsDescription"),
      keywords: ["turns", "max", "conversation", "limit", "chat"],
      sectionId: SECTION_IDS.ai,
      sectionLabel: sections.ai,
    },
    {
      id: SETTING_IDS.maxToolCallSteps,
      label: tSettings("ai.maxToolCallSteps"),
      description: tSettings("ai.maxToolCallStepsDescription"),
      keywords: [
        "tool",
        "calls",
        "max",
        "limit",
        "agent",
        "steps",
        "local",
        "loop",
      ],
      sectionId: SECTION_IDS.ai,
      sectionLabel: sections.ai,
    },
    {
      id: SETTING_IDS.contextCompaction,
      label: tSettings("ai.contextCompaction"),
      description: tSettings("ai.contextCompactionDescription"),
      keywords: [
        "context",
        "compaction",
        "compact",
        "summarize",
        "tokens",
        "window",
        "memory",
      ],
      sectionId: SECTION_IDS.ai,
      sectionLabel: sections.ai,
    },
    {
      id: SECTION_IDS.providers,
      label: sections.providers,
      description: "Configure AI model providers and API keys",
      keywords: [
        "provider",
        "model",
        "api key",
        "openai",
        "anthropic",
        "claude",
        "gpt",
        "gemini",
        "llm",
      ],
      sectionId: SECTION_IDS.providers,
      sectionLabel: sections.providers,
    },
    {
      id: SETTING_IDS.telemetry,
      label: tSettings("telemetry.title"),
      description: tSettings("telemetry.description"),
      keywords: [
        "telemetry",
        "analytics",
        "usage",
        "data",
        "privacy",
        "tracking",
      ],
      sectionId: SECTION_IDS.telemetry,
      sectionLabel: sections.telemetry,
    },
    {
      id: SETTING_IDS.github,
      label: tHome("integrations.github.title"),
      description: "Connect your GitHub account",
      keywords: ["github", "git", "integration", "connect", "account"],
      sectionId: SECTION_IDS.integrations,
      sectionLabel: sections.integrations,
    },
    {
      id: SETTING_IDS.vercel,
      label: tHome("integrations.vercel.title"),
      description: "Connect your Vercel account for deployments",
      keywords: ["vercel", "deploy", "integration", "hosting", "connect"],
      sectionId: SECTION_IDS.integrations,
      sectionLabel: sections.integrations,
    },
    {
      id: SETTING_IDS.supabase,
      label: tHome("integrations.supabase.title"),
      description: "Connect your Supabase project",
      keywords: [
        "supabase",
        "database",
        "integration",
        "backend",
        "connect",
        "postgres",
      ],
      sectionId: SECTION_IDS.integrations,
      sectionLabel: sections.integrations,
    },
    {
      id: SETTING_IDS.neon,
      label: tHome("integrations.neon.title"),
      description: "Connect your Neon database",
      keywords: [
        "neon",
        "database",
        "integration",
        "postgres",
        "connect",
        "serverless",
      ],
      sectionId: SECTION_IDS.integrations,
      sectionLabel: sections.integrations,
    },
    {
      id: SECTION_IDS.agentPermissions,
      label: sections.agentPermissions,
      description: tSettings("agentPermissions.description"),
      keywords: [
        "agent",
        "permissions",
        "tools",
        "approve",
        "allow",
        "consent",
      ],
      sectionId: SECTION_IDS.agentPermissions,
      sectionLabel: sections.agentPermissions,
    },
    {
      id: SECTION_IDS.toolsMcp,
      label: sections.toolsMcp,
      description: "Configure MCP servers and environment variables",
      keywords: [
        "mcp",
        "tools",
        "server",
        "model context protocol",
        "environment",
      ],
      sectionId: SECTION_IDS.toolsMcp,
      sectionLabel: sections.toolsMcp,
    },
    {
      id: SETTING_IDS.nativeGit,
      label: tSettings("experiments.enableNativeGit"),
      description: tSettings("experiments.enableNativeGitDescription"),
      keywords: ["git", "native", "experiment", "beta", "performance"],
      sectionId: SECTION_IDS.experiments,
      sectionLabel: sections.experiments,
    },
    {
      id: SETTING_IDS.blockUnsafeNpmPackages,
      label: tSettings("experiments.blockUnsafeNpmPackages"),
      description: tSettings("experiments.blockUnsafeNpmPackagesDescription"),
      keywords: ["socket", "npm", "firewall", "package", "unsafe", "security"],
      sectionId: SECTION_IDS.experiments,
      sectionLabel: sections.experiments,
    },
    {
      id: SETTING_IDS.enableMcpServersForBuildMode,
      label: tSettings("experiments.enableMcpServersForBuildMode"),
      description: tSettings(
        "experiments.enableMcpServersForBuildModeDescription",
      ),
      keywords: ["mcp", "build", "agent", "tools", "experiment", "server"],
      sectionId: SECTION_IDS.experiments,
      sectionLabel: sections.experiments,
    },
    {
      id: SETTING_IDS.enableSelectAppFromHomeChatInput,
      label: tSettings("experiments.enableSelectAppFromHomeChatInput"),
      description: tSettings(
        "experiments.enableSelectAppFromHomeChatInputDescription",
      ),
      keywords: ["app", "select", "home", "chat", "experiment", "input"],
      sectionId: SECTION_IDS.experiments,
      sectionLabel: sections.experiments,
    },
    {
      id: SETTING_IDS.reset,
      label: tSettings("dangerZone.resetEverything"),
      description: tSettings("dangerZone.resetDescription"),
      keywords: ["reset", "delete", "clear", "wipe", "danger", "destructive"],
      sectionId: SECTION_IDS.dangerZone,
      sectionLabel: sections.dangerZone,
    },
  ];
}
